# ICSC 2026 paper "One Timeline, Many Renderings".
#
#   make              build paper.pdf (default)
#   make example      regenerate figures + example material via temporal-system
#   make check        syntax-check the generated .csd files with csound
#   make help         list every target
#
# Requires TeX Live (latexmk/pdflatex). The `example` and `check` targets
# additionally need wolframscript, csound, and a local checkout of the
# temporal-system paclet (see TEMPORAL_REPO below).

LATEXMK       ?= latexmk
LATEXMKFLAGS  ?= -pdf -interaction=nonstopmode -halt-on-error
WOLFRAMSCRIPT ?= wolframscript
CSOUND        ?= csound

PAPER   := paper
FIGURE  := figures/timeline_export.pdf
DISTZIP := icsc2026-submission.zip

# Must match repoRoot at the top of tools/make_example.wls.
TEMPORAL_REPO ?= /Users/master/Documents/GitHub/temporal-system

# Everything below is (re)generated by tools/make_example.wls.
CSD_FILES := example/timeline_example.csd \
             example/timeline_example_click.csd \
             example/paper_note.csd \
             example/paper_click.csd

.DEFAULT_GOAL := all
.PHONY: all paper example check watch view dist clean distclean help

all: paper ## Build the paper (default)

paper: $(PAPER).pdf ## Build paper.pdf with latexmk

$(PAPER).pdf: $(PAPER).tex llncs.cls $(FIGURE)
	$(LATEXMK) $(LATEXMKFLAGS) $(PAPER).tex

# The figure is committed; this rule only fires if it goes missing.
# Regenerating it requires the full example pipeline.
$(FIGURE):
	$(MAKE) example

# The script path must be absolute: make_example.wls SetDirectory's into
# temporal-system, and a relative ScriptCommandLine there triggers a harmless
# AbsoluteFileName::fdnfnd warning from the paclet's test guards.
example: ## Regenerate figures/ + example/ (needs temporal-system, wolframscript, csound)
	@test -d "$(TEMPORAL_REPO)" || { \
		echo "error: temporal-system checkout not found at $(TEMPORAL_REPO)"; \
		echo "       (clone it there, or fix repoRoot in tools/make_example.wls"; \
		echo "        and TEMPORAL_REPO in this Makefile)"; \
		exit 1; }
	$(WOLFRAMSCRIPT) -file "$(CURDIR)/tools/make_example.wls"

check: ## Syntax-check the generated .csd files with csound
	@set -e; for f in $(CSD_FILES); do \
		test -f "$$f" || { echo "missing $$f -- run 'make example' first"; exit 1; }; \
		printf '%s ... ' "$$f"; \
		if $(CSOUND) --syntax-check-only "$$f" >/dev/null 2>&1; then \
			echo "ok"; \
		else \
			echo "FAILED"; $(CSOUND) --syntax-check-only "$$f"; exit 1; \
		fi; \
	done; echo "all .csd files pass csound --syntax-check-only"

watch: ## Rebuild the paper continuously on save (latexmk -pvc)
	$(LATEXMK) $(LATEXMKFLAGS) -pvc $(PAPER).tex

view: paper ## Build and open paper.pdf
	open $(PAPER).pdf

dist: $(PAPER).pdf ## Package sources + PDF into icsc2026-submission.zip
	rm -f $(DISTZIP)
	zip $(DISTZIP) $(PAPER).tex llncs.cls $(FIGURE) $(PAPER).pdf
	@echo "wrote $(DISTZIP)"

clean: ## Remove LaTeX auxiliary files (keeps paper.pdf)
	$(LATEXMK) -c

distclean: clean ## Also remove paper.pdf and the submission zip
	$(LATEXMK) -C
	rm -f $(DISTZIP)

help: ## Show this help
	@awk 'BEGIN{FS=":.*##"} /^[a-zA-Z0-9_.-]+:.*##/{printf "  %-12s%s\n", $$1, $$2}' $(MAKEFILE_LIST)
